// Run with Bun and Playwright installed outside the application's dependency tree:
// NODE_PATH=/path/to/browser-tools/node_modules bun scripts/browser-smoke.mjs
// Requires the dev host serving a disposable copy of examples/Welcome on :9240.
import { chromium } from 'playwright';
import { strict as assert } from 'node:assert';

const browser = await chromium.launch({ executablePath: process.env.CHROMIUM || '/usr/bin/chromium', headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1380, height: 900 } });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
try {
  await page.clock.setFixedTime(new Date(2026, 8, 24, 12));
  await page.goto('http://127.0.0.1:9240');
  await page.locator('#agenda').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#workspace-name').innerText(), process.env.WORKSPACE_NAME || 'orbitalnote-smoke');
  assert.equal(await page.locator('#menu').getAttribute('aria-expanded'), 'true');
  await page.locator('#menu').click();
  assert.equal(await page.locator('#sidebar').isVisible(), false);
  assert.equal(await page.locator('#menu').getAttribute('aria-label'), 'Show left sidebar');
  assert.equal(await page.locator('#ribbon [data-view="search"]').isVisible(), true);
  await page.reload();
  await page.locator('#agenda').waitFor({ state: 'visible' });
  assert.equal(await page.locator('#sidebar').isVisible(), false);
  await page.keyboard.press('Control+Shift+l');
  await page.locator('#sidebar').waitFor({ state: 'visible' });
  await page.screenshot({ path: '/tmp/opencode/orbitalnote-agenda.png' });
  await page.locator('#tree [data-open="inbox.org"]').click();
  await page.locator('#source').waitFor({ state: 'visible' });
  const original = await page.locator('#source').evaluate(el => el.value);
  assert.match(original, /Make room/);
  await page.locator('#context').waitFor({ state: 'visible' });
  const initialWidth = await page.locator('#panes').evaluate(el => el.clientWidth);
  await page.locator('#context-toggle').click();
  assert.equal(await page.locator('#context').isVisible(), false);
  assert.ok(await page.locator('#panes').evaluate(el => el.clientWidth) > initialWidth);
  assert.equal(await page.locator('#source').evaluate(el => el.value), original);
  await page.keyboard.press('Control+Shift+r');
  await page.locator('#context').waitFor({ state: 'visible' });
  await page.locator('#source').fill(original + '\n* TODO Browser smoke test\n');
  await page.keyboard.press('Control+s');
  await page.waitForFunction(() => document.getElementById('save-state').textContent === 'Saved to disk');
  const disk = await page.evaluate(async () => {
    const api = async (method, q={}) => (await fetch('/api', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({method,...q}) })).json();
    const state=await api('Status'); return await api('Read',{id:state.id,path:'inbox.org'});
  });
  assert.match(disk.source, /Browser smoke test/);
  await page.locator('#preview-toggle').click();
  await page.locator('#preview').waitFor({ state: 'visible' });
  assert.match(await page.locator('#preview').innerText(), /Browser smoke test/);
  await page.locator('#preview-toggle').click();
  await page.locator('#source').fill(disk.source + '\nUnsaved local thought\n');
  await page.evaluate(async () => {
    const api = async (method, q={}) => (await fetch('/api', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({method,...q}) })).json();
    const state=await api('Status'), note=await api('Read',{id:state.id,path:'inbox.org'});
    await api('Save',{id:state.id,path:'inbox.org',source:note.source+'\nExternal change\n',revision:note.revision});
  });
  await page.locator('#conflict').waitFor({ state: 'visible' });
  assert.match(await page.locator('#source').evaluate(el => el.value), /Unsaved local thought/);
  assert.equal(await page.locator('#save').isDisabled(), true);
  await page.locator('#reload-file').click();
  await page.locator('#modal-submit').click();
  await page.locator('#conflict').waitFor({ state: 'hidden' });
  assert.match(await page.locator('#source').evaluate(el => el.value), /External change/);
  await page.locator('[data-view="search"]').click();
  await page.locator('#search-input').fill('Browser smoke');
  await page.locator('.search-result').first().waitFor();
  await page.locator('[data-view="calendar"]').click();
  assert.equal(await page.locator('.weekday').count(), 7);
  await page.locator('[data-calendar="year"]').click();
  assert.equal(await page.locator('.mini-month').count(), 12);
  await page.locator('[data-calendar="month"]').click();
  const event = page.locator('.calendar-event[data-open="inbox.org"]').first();
  await event.dragTo(page.locator('[data-drop-date="2026-09-26"]'));
  await page.waitForFunction(() => document.getElementById('notice').textContent.includes('Updated the plaintext timestamp'));
  const moved = await page.evaluate(async () => {
    const api = async (method, q={}) => (await fetch('/api', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({method,...q}) })).json();
    const state=await api('Status'); return await api('Read',{id:state.id,path:'inbox.org'});
  });
  assert.match(moved.source, /SCHEDULED: <2026-09-26 Sat>/);
  await page.locator('#calendar-capture').click();
  await page.locator('#modal input[name="title"]').fill('Captured through calendar');
  await page.locator('#modal input[name="path"]').fill('inbox.org');
  await page.locator('#modal input[name="date"]').fill('2026-09-28');
  await page.locator('#modal-submit').click();
  await page.locator('.calendar-event', { hasText:'Captured through calendar' }).waitFor();
  await page.screenshot({ path: '/tmp/opencode/orbitalnote-calendar.png' });
  await page.keyboard.press('Control+k');
  await page.locator('#palette-input').fill('jrn');
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => document.getElementById('document-name')?.textContent === 'journal');
  await page.locator('#preview-toggle').click();
  await page.screenshot({ path: '/tmp/opencode/orbitalnote-document.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.locator('#sidebar').isVisible(), false);
  assert.equal(await page.locator('#context').isVisible(), false);
  await page.locator('#context-toggle').click();
  await page.locator('#context').waitFor({ state: 'visible' });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#context').isVisible(), false);
  await page.locator('#menu').click();
  await page.locator('#sidebar').waitFor({ state: 'visible' });
  await page.locator('[data-view="settings"]').click();
  assert.equal(await page.locator('#sidebar').isVisible(), false);
  await page.locator('#theme').selectOption('dark');
  await page.screenshot({ path: '/tmp/opencode/orbitalnote-mobile-dark.png' });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  assert.deepEqual(errors, []);
  console.log('PASS: sidebar controls/persistence/keyboard/mobile drawers, source/save, preview, dirty conflict, reload, search, calendar, timestamp drag, task capture, quick-open, dark theme.');
} finally { await browser.close(); }
