// Run only against app/dev with a disposable workspace.
import { chromium } from 'playwright';
import { strict as assert } from 'node:assert';
const base = process.env.BASE_URL || 'http://127.0.0.1:9256';
const browser = await chromium.launch({headless:true, executablePath: process.env.CHROMIUM || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
let page;
try {
  page = await browser.newPage({viewport:{width:1400,height:950}});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  const api=async(method,q={})=>{const r=await page.request.post(base+'/api',{data:{method,...q}}); const v=await r.json(); assert.ok(r.ok(),JSON.stringify(v)); return v;};
  const state=await api('Status'), path='interaction.org';
  const original='* TODO Focus task\nSCHEDULED: <2026-09-29 Tue>\n- [ ] First step\n  - [X] Nested step\n** Child\nBody\n* TODO Other task\nDEADLINE: <2026-09-30 Wed>\n'+Array.from({length:100},(_,i)=>'Line '+i).join('\n')+'\n';
  const prior=state.files.some(f=>f.path===path)?await api('Read',{id:state.id,path}):null;
  await api('Save',{id:state.id,path,source:original,revision:prior?.revision||''});
  const repeatPath='repeat-review.org', repeatOld=state.files.some(f=>f.path===repeatPath)?await api('Read',{id:state.id,path:repeatPath}):null;
  await api('Save',{id:state.id,path:repeatPath,source:'* TODO Repeat task\nSCHEDULED: <2026-09-29 Tue +1w>\n',revision:repeatOld?.revision||''});
  for (const folder of ['Review','Review/Nested']) if (!state.files.some(f=>f.path===folder)) await api('Mkdir',{id:state.id,path:folder});
  const nestedPath='Review/Nested/note.org';
  if (!state.files.some(f=>f.path===nestedPath)) await api('Save',{id:state.id,path:nestedPath,source:'* Nested note\n',revision:''});
  await page.clock.setFixedTime(new Date(2026,8,29,12));
  await page.goto(base); await page.locator('#tree [data-open="interaction.org"]').click();
  const doc=page.locator('.ui-document[data-path="interaction.org"]'), editor=doc.locator('[data-ui="source"]');
  await editor.click();
  await page.locator('#ribbon [data-view="agenda"]').click();
  await page.keyboard.type('THIS MUST NOT EDIT A HIDDEN NOTE');
  assert.equal(await editor.evaluate(el=>el.value),original);
  assert.ok(await doc.evaluate(el=>el.closest('.tab-surface').inert));
  await page.locator('[data-filter="all"]').click();
  await page.locator('#agenda-query').fill('Focus task');
  await page.locator('#agenda-query-builder summary').click();
  await page.locator('[data-view-name]').fill('Focus only');
  await page.locator('[data-save-view]').click();
  await page.locator('#agenda-query-builder summary').click();
  await page.locator('#agenda-minimal').click();
  assert.ok(await page.locator('#agenda-query').isHidden());
  assert.equal(await page.locator('#agenda-list .agenda-entry').count(),1);
  await page.locator('#agenda-minimal').click();
  assert.equal(await page.locator('#agenda-query').inputValue(),'Focus task');
  await page.getByRole('button',{name:'Clock in to Focus task',exact:true}).click();
  await page.locator('.clocked').waitFor();
  assert.equal(await page.locator('.clocked .agenda-entry').count(),1);
  assert.match((await api('Read',{id:state.id,path})).source,/:LOGBOOK:\nCLOCK: \[/);
  await page.locator('#ribbon [data-view="calendar"]').click();
  await page.locator('#calendar-view').selectOption('Focus only');
  assert.ok(await page.locator('#calendar-clock').isVisible());
  assert.equal(await page.locator('.calendar-event').filter({hasText:'Other task'}).count(),0);
  await page.locator('[data-tab-select="file:interaction.org"]').click();
  assert.ok(await doc.locator('[data-ui="note-clock"]').isVisible());
  assert.equal(await doc.locator('[data-ui="note-clock"] button').count(),0);
  await page.locator('#ribbon [data-view="agenda"]').click();
  await page.getByRole('button',{name:'Clock out of Focus task',exact:true}).first().click();
  await page.locator('[data-tab-select="file:interaction.org"]').click();
  await doc.locator('[data-ui="note-clock"]').waitFor({state:'hidden'});
  assert.match((await api('Read',{id:state.id,path})).source,/\]--\[.*\] => /);
  await doc.locator('[data-ui="preview-toggle"]').click();
  await doc.locator('.preview-checkbox').first().click();
  await page.waitForFunction(()=>document.querySelector('.ui-document[data-path="interaction.org"] [data-ui="source"]').value.includes('- [X] First step'));
  await doc.locator('[data-ui="preview-toggle"]').click();
  await editor.evaluate(el=>{el.focus();el.setSelectionRange(el.value.indexOf('First step')+'First step'.length,el.value.indexOf('First step')+'First step'.length);});
  await page.keyboard.press('Enter');
  assert.match(await editor.evaluate(el=>el.value),/First step\n- \[ \] /);
  await page.locator('#ribbon [data-view="settings"]').click();
  await page.locator('#line-numbers').selectOption('relative');
  await page.locator('#monospace-mode').check();
  await page.locator('#vi-mode').check();
  await page.locator('[data-tab-select="file:interaction.org"]').click();
  assert.ok(await doc.locator('.cm-lineNumbers').isVisible());
  await editor.evaluate(el=>{el.focus();el.setSelectionRange(0,0);});
  const gutterBefore=await doc.locator('.cm-lineNumbers').innerText();
  await editor.evaluate(el=>el.setSelectionRange(el.value.indexOf('- ['),el.value.indexOf('- [')));
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  assert.notEqual(await doc.locator('.cm-lineNumbers').innerText(),gutterBefore);
  await editor.evaluate(el=>{el.focus();el.setSelectionRange(0,0);});
  const before=await editor.evaluate(el=>el.selectionStart);
  await page.keyboard.press('Control+d');
  assert.ok(await editor.evaluate(el=>el.selectionStart)>before);
  assert.ok(await editor.evaluate(el=>el.scrollTop>0));
  await page.keyboard.press('Control+u');
  await editor.evaluate(el=>{el.setSelectionRange(el.value.indexOf('Focus task'),el.value.indexOf('Focus task')+5);});
  await page.keyboard.press('R'); await page.keyboard.press('z');
  assert.match(await editor.evaluate(el=>el.value),/zzzzz task/);
  await page.keyboard.press('R'); await page.keyboard.press('5');
  assert.match(await editor.evaluate(el=>el.value),/5zzzz task/);
  await page.keyboard.press('Meta+p');
  await page.locator('#palette-input').fill('Find file');
  await page.keyboard.press('Control+n'); await page.keyboard.press('Control+p');
  const rect=await page.locator('#palette').boundingBox(); await page.mouse.click(rect.x-10,rect.y+10);
  assert.ok(await page.locator('#palette').isHidden());
  await doc.locator('[data-ui="save-state"]').filter({hasText:'Saved to disk'}).waitFor();
  await page.locator('#ribbon [data-view="calendar"]').click();
  await page.locator('#calendar-view').selectOption('');
  const transfer=await page.evaluateHandle(()=>new DataTransfer());
  await page.locator('.calendar-event').filter({hasText:'Other task'}).first().dispatchEvent('dragstart',{dataTransfer:transfer});
  await page.locator('[data-drop-date="2026-10-01"]').first().dispatchEvent('drop',{dataTransfer:transfer});
  await page.waitForFunction(()=>document.querySelector('[data-drop-date="2026-10-01"]')?.textContent.includes('Other task'));
  assert.match((await api('Read',{id:state.id,path})).source,/DEADLINE: <2026-10-01/);
  await page.locator('[data-calendar="week"]').click();
  assert.ok(await page.locator('.time-day-header.is-today').isVisible());
  const eventBox = await page.locator('.calendar-event').filter({hasText:'Other task'}).first().boundingBox();
  const dayBox = await page.locator('.all-day-row [data-drop-date="2026-09-30"]').boundingBox();
  await page.mouse.move(eventBox.x + eventBox.width / 2, eventBox.y + eventBox.height / 2);
  await page.mouse.down(); await page.mouse.move(dayBox.x + dayBox.width / 2, dayBox.y + dayBox.height / 2, { steps: 8 }); await page.mouse.up();
  await page.waitForFunction(()=>document.querySelector('.all-day-row [data-drop-date="2026-09-30"]')?.textContent.includes('Other task'));
  await page.locator('#tree [data-open="repeat-review.org"]').click();
  const repeat=page.locator('.ui-document[data-path="repeat-review.org"]');
  await repeat.locator('.heading-menu-button').first().click();
  assert.equal(await page.locator('dialog.heading-actions-menu').evaluate(el=>document.activeElement===el),true);
  await page.getByRole('button',{name:'Edit task…',exact:true}).click();
  assert.equal(await page.locator('#modal [name="repeater"]').inputValue(),'+1w');
  await page.locator('#modal [name="repeater"]').fill('+2w');
  await page.locator('#modal-submit').click();
  await page.waitForFunction(()=>document.querySelector('.ui-document[data-path="repeat-review.org"] [data-ui="source"]').value.includes('+2w'));
  await repeat.locator('[data-ui="save-state"]').filter({hasText:'Saved to disk'}).waitFor();
  await page.locator('#ribbon [data-view="agenda"]').click();
  await page.locator('#agenda-query').fill('Repeat task');
  await page.getByRole('button',{name:'Mark Repeat task as done',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('#agenda-list')?.textContent.includes('October 13'));
  const repeated=await api('Read',{id:state.id,path:repeatPath});
  assert.match(repeated.source,/SCHEDULED: <2026-10-13 Tue \+2w>/);
  assert.equal(repeated.headings[0].history.length,1);
  await page.locator('#ribbon [data-view="calendar"]').click();
  await page.locator('[data-calendar="month"]').click();
  assert.ok(await page.locator('.calendar-event.completed').filter({hasText:'Repeat task'}).isVisible());
  await page.reload();
  await page.locator('#tree [data-open="interaction.org"]').click();
  assert.ok(await page.locator('.ui-document[data-path="interaction.org"] .cm-lineNumbers').isVisible());
  await page.locator('#tree details').evaluateAll(nodes=>nodes.forEach(el=>el.open=true));
  const rootBox=await page.locator('#tree [data-open="interaction.org"]').boundingBox(), nestedBox=await page.locator('#tree [data-open="Review/Nested/note.org"]').boundingBox();
  assert.ok(nestedBox.x>rootBox.x+20,'Nested files must be visibly indented');
  if (await doc.locator('[data-ui="context"]').isHidden()) await page.locator('#context-toggle').click();
  await doc.locator('[data-ui="outline-toggle-all"]').click();
  assert.equal(await doc.locator('[data-ui="outline"] details[open]').count(),0);
  await doc.locator('[data-ui="outline-toggle-all"]').click();
  assert.ok(await doc.locator('[data-ui="outline"] details[open]').count()>0);
  await doc.locator('.editor-heading-fold').first().click();
  await editor.evaluate(el=>{const pos=el.value.indexOf('First step');el.setSelectionRange(pos,pos);});
  assert.equal(await doc.locator('.editor-heading-fold').first().getAttribute('aria-expanded'),'false');
  await page.setViewportSize({width:390,height:844});
  const foldBox=await doc.locator('.editor-heading-fold').first().boundingBox(), ribbonBox=await page.locator('#ribbon').boundingBox();
  assert.ok(foldBox.x>=ribbonBox.x+ribbonBox.width,'Mobile fold control must clear the ribbon');
  assert.deepEqual(errors,[]);
  console.log('PASS: hidden-tab focus isolation, minimal agenda query, calendar saved views, Org clocks, source/preview checklists, line numbers/persistence, monospace, Vi scrolling/replace, modal keys/backdrop, deadline drag in month/week, repeater editing/completion/history.');
} catch (error) {
  console.error('Notice:',await page.locator('#notice').textContent());
  await page.screenshot({path:'/private/var/folders/0y/thqb3_1s69nf62hymzpf94p40000gn/T/opencode/interaction-failure.png'});
  throw error;
} finally {await browser.close();}
